### ISSUE TITLE
Fatal error: Call to undefined method mysqli_result::fetch() in C:\xampp\htdocs\19\Core\core.php on line 65

### ISSUE THREAD

**Issue by ogamemaster** [xnova-legacies/2016#1]
?????

**Comment by mandalorien** [comment]
sorry but , I start the project from 0 ago pounds Relationship of apparant bugs .
If you want to participate , do not hesitate .


désoler mais , je recommence le projet depuis 0 , il y a trops de bugs apparant , si tu veux participer , n'hésites pas .
